org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true

minecraft_version=1.21.1
minecraft_version_range=[1.21,1.22)
neo_version=21.1.80
neo_version_range=[21.1.0,)
loader_version_range=[4,)

mod_id=immersive_weathering
mod_name=Immersive Weathering (Icicles Only)
mod_license=LGPL-3.0
mod_version=1.21.1-1.0.0
mod_group_id=com.ordana.immersive_weathering
mod_authors=Ordana, MehVahdJukaar